services:
  - type: web
    name: ocr-whisper-api
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ocr_api:app --host 0.0.0.0 --port 8000
